#!/bin/bash
# Rio: Load CSV from stdin into R as a data frame, execute given commands, and get the output as CSV or PNG on stdout
#
# Example usage:
# curl -s 'https://raw.github.com/pydata/pandas/master/pandas/tests/data/iris.csv' > iris.csv
# < iris.csv Rio -e 'summary(df)'
# < iris.csv Rio -se 'sqldf("select Name from df where df.SepalLength > 7")'
# < iris.csv Rio -ge 'g+geom_point(aes(x=SepalLength,y=SepalWidth,colour=Name))' > iris.png
#
# Dependency: R (with optionally the R packages ggplot2, plyr, and sqldf)
#
# Author: http://jeroenjanssens.com

usage() {
cat << EOF
Rio: Load CSV from stdin into R as a data frame, execute given commands, and get the output as CSV on stdout

usage: Rio OPTIONS

OPTIONS:
   -d      Delimiter
   -e      Commands to execute
   -h      Show this message
   -g      Import ggplot2
   -n      CSV has no header
   -p      Import plyr
   -s      Import sqldf
   -v      Verbose

EOF
}

callR() {
	Rscript --vanilla -e "df<-read.csv('${IN}',header=${HEADER},sep='${DELIMITER}',stringsAsFactors=F);${REQUIRES}${SCRIPT}last<-.Last.value;if(is.data.frame(last)){write.table(last,'${OUT}',sep=',',quote=F,row.names=F,col.names=${HEADER});}else if(exists('is.ggplot')&&is.ggplot(last)){ggsave('${OUT}',last,dpi=72);}else{sink('${OUT}');print(last);}"
}

SCRIPT=
REQUIRES=
DELIMITER=","
HEADER="T"
VERBOSE=false
IN=$(mktemp)
OUT=$(mktemp).png
while getopts "d:hgnpsve:" OPTION
do
	case $OPTION in
		d)
			DELIMITER=$OPTARG
			;;
		e)
			SCRIPT=$OPTARG
			if ! echo $SCRIPT | grep -qe "; *$"
			then
				SCRIPT="${SCRIPT};"
			fi
			;;
		h)
			usage
			exit 1
			;;
		g)
			REQUIRES="${REQUIRES}require(ggplot2);g<-ggplot(df);"
			;;
		n)
			HEADER="F"
			;;
		p)
			REQUIRES="${REQUIRES}require(plyr);"
			;;
		s)
			REQUIRES="${REQUIRES}require(sqldf);"
			;;
		v)
			VERBOSE=true
			;;
		?)
			usage
			exit
		;;
	esac
done

cat /dev/stdin > $IN
if $VERBOSE
then
	callR
else
	callR >/dev/null 2>&1
fi
cat $OUT
rm $IN $OUT
rm -f Rplots.pdf
