# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "data-science-toolbox"
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.provision :shell, :path => "bootstrap.sh"
end
