---
suppress-bibliography: true
---

```{r console_start, include=FALSE}
console_start()
```

```{console setup_history, include=FALSE}
 export CHAPTER="03"
 export HISTFILE=/history/history_${CHAPTER}
 rm -f $HISTFILE
```

```{console install_pup_arm64, include=FALSE}
curl -sL https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_arm64.zip -o pup.zip
unzip pup.zip
sudo mv pup /usr/bin/
rm pup.zip
```

# Obtaining Data {#chapter-3-obtaining-data}

This chapter deals with the first step of the OSEMN model: obtaining data.
After all, without any data, there is not much data science that we can do.
I assume that the data you need to solve your data science problem already exists.
Your first task is to get this data onto your computer (and possibly also inside the Docker container) in a form that you can work with.

According to the Unix philosophy, text is a universal interface.
Almost every command-line tool takes text as input, produces text as output, or both.
This is the main reason why command-line tools can work so well together.
However, as we'll see, even just text can come in multiple forms.

Data can be obtained in several ways---for example by downloading it from a server, querying a database, or connecting to a Web API.
Sometimes, the data comes in a compressed form or in a binary format such as a Microsoft Excel Spreadsheet.
In this chapter, I discuss several tools that help tackle this from the command line, including: `curl`[@curl], `in2csv`[@in2csv], `sql2csv`[@sql2csv], and `tar`[@tar].


## Overview

In this chapter, you’ll learn how to:

- Copy local files to the Docker image
- Download data from the Internet
- Decompress files
- Extract data from spreadsheets
- Query relational databases
- Call web APIs

This chapter starts with the following files:

```{console cd}
cd /data/ch03
l
```

The instructions to get these files are in [Chapter 2](#chapter-2-getting-started).
Any other files are either downloaded or generated using command-line tools.


## Copying Local Files to the Docker Container

A common situation is that you already have the necessary files on your own computer.
This section explains how you can get those files into the Docker container.

I mentioned in [Chapter 2](#chapter-2-getting-started) that the Docker container is an isolated virtual environment.
Luckily there is one exception to that: files can be transferred in and out the Docker container.
The local directory from which you ran `docker run`, is mapped to a directory in the Docker container.
This directory is called */data*.
Note that this is not the home directory, which is */home/dst*.

If you have one or more files on your local computer, and you want to apply some command-line tools to them, all you have to do is copy or move the files to that mapped directory.
Let’s assume that you have a file called *logs.csv* in your Downloads directory.

If you're running Windows, open the command prompt or PowerShell and run the following two commands:

```powershell
> cd %UserProfile%\Downloads
> copy logs.csv MyDataScienceToolbox\
```

If you are running Linux or macOS, open a terminal and execute the following command on your operating system (and not inside the Docker container):

```{console cp}
cp ~/Downloads/logs.csv ~/my-data-science-toolbox#! enter=FALSE
```

```{console cp_cancel, include=FALSE}
C-C#! literal=FALSE
```

You can also drag-and-drop the file into the right directory using a graphical file manager such as Windows Explorer or macOS Finder.


## Downloading from the Internet

The Internet provides, without a doubt, the largest resource for interesting data.
The command-line tool `curl` can be considered the command line's Swiss Army knife when it comes to downloading data from the Internet.


### Introducing `curl`

When you browse to a URL, which stands for *uniform resource locator*, your browser interprets the data it downloads.
For example, the browser renders HTML files, plays video files automatically, and shows PDF files.
However, when you use `curl` to access a URL, it downloads the data and, by default, prints it to standard output.
`curl` doesn't do any interpretation, but luckily other command-line tools can be used to process the data further.

The easiest invocation of `curl` is to specify a URL as a command-line argument.
Let's, try downloading an article from Wikipedia:

```{console curl_simple, callouts=2}
curl "https://en.wikipedia.org/wiki/List_of_windmills_in_the_Netherlands" |
trim
```
<1> Remember, `trim` is used only to make the output fit nicely in the book.

As you can see, `curl` downloads the raw HTML returned by Wikipedia's server; no interpretation is being done and all the contents is immediately printed on standard output.
Because of the URL, you'd think that this article would list all the windmills in the Netherlands.
However, there are apparently so many windmills left that each province has its own page.
Fascinating.

By default, `curl` outputs a progress meter that shows the download rate and the expected time of completion.
This output isn't written to standard output, but a separate channel, known as *standard error*, so this doesn't interfere when you add another tool to the pipeline.
While this information can be useful when downloading very large files, I usually find it distracting, so I specify the `-s` option to *silence* this output.

```{console curl_silent}
curl -s "https://en.wikipedia.org/wiki/List_of_windmills_in_Friesland" |
pup -n 'table.wikitable tr' # <1>
```
<1> I'll discuss `pup`[@pup], a handy tool for scraping websites, in more detail in [Chapter 5](#chapter-5-scrubbing-data).

And what do you know, there are apparently 234 windmills in the province of Friesland alone!


### Saving

You can let `curl` save the output to a file by adding the `-O` option.
The filename will be based on the last part of the URL.

```{console curl_save}
curl -s "https://en.wikipedia.org/wiki/List_of_windmills_in_Friesland" -O
l
```

If you don't like that filename then you can use the `-o` option together with a filename or redirect the output to a file yourself:

```{console curl_redirect}
curl -s "https://en.wikipedia.org/wiki/List_of_windmills_in_Friesland" > friesland.html
```


### Other Protocols

In total, `curl` supports [more than 20 protocols](https://ec.haxx.se/protocols/protocols-curl).
To download from an FTP server, which stands for File Transfer Protocol, you use `curl` the same way.
Here I download the file *welcome.msg* from *ftp.gnu.org*:

```{console curl_ftp}
curl -s "ftp://ftp.gnu.org/welcome.msg" | trim
```

If the specified URL is a directory, `curl` will list the contents of that directory.
When the URL is password protected, you can specify a username and a password as follows with the `-u` option.

Or how about the DICT protocol, which allows you to access various dictionaries and lookup definitions.
Here's the definition of "windmill" according to the Collaborative International Dictionary of English:

```{console curl_dict}
curl -s "dict://dict.org/d:windmill" | trim
```

When downloading data from the Internet, however, the protocol will most likely be HTTP, so the URL will start with either *http://* or *https://*.


### Following Redirects

When you access a shortened URL, such as the ones that start with *http://bit.ly/* or *http://t.co/*, your browser automatically redirects you to the correct location.
With `curl`, however, you need to specify the `-L` or `--location` option in order to be redirected.
If you don't, you can get something like:

```{console curl_bitly}
curl -s "https://bit.ly/2XBxvwK"
```

Sometimes you get nothing back, just like when we follow the URL mentioned above:

```{console curl_youtube}
curl -s "https://youtu.be/dQw4w9WgXcQ"
```

By specifying the `-I` or `--head` option, `curl` fetches only the HTTP header of the response, which allows you to inspect the status code and other information returned by the server.

```{console curl_head}
curl -sI "https://youtu.be/dQw4w9WgXcQ" | trim
```

The first line shows the protocol followed by the HTTP status code, which is 303 in this case.
You can also see the location this URL redirects to.
Inspecting the header and getting the status code is a useful debugging tool in case `curl` does not give you the expected result.
Other common HTTP status codes include 404 (not found) and 403 (forbidden).
Wikipedia has a page that lists [all HTTP status codes](http://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

In summary, `curl` is a useful command-line tool for downloading data from the Internet.
Its three most common options are `-s` to silence the progress meter, `-u` to specify a username and password, and `-L` to automatically follow redirects.
See its man page for more information (and to make your head spin):

```{console curl_man}
man curl | trim 20
```


## Decompressing Files

If the original dataset is very large or it's a collection of many files, the file may be a compressed archive.
Datasets which contain many repeated values (such as the words in a text file or the keys in a JSON file) are especially well suited for compression.

Common file extensions of compressed archives are: *.tar.gz*, *.zip*, and *.rar*.
To decompress these, you would use the command-line tools `tar`, `unzip` [@unzip], and `unrar` [@unrar], respectively.
(There are a few more, though less common, file extensions for which you would need yet other tools.)

Let's take *tar.gz* (pronounced as "gzipped tarball") as an example.
In order to extract an archive named *logs.tar.gz*, you would use the following incantation:

```{console tar_x}
tar -xzf logs.tar.gz # <1> #! enter=FALSE
```
<1> It's common to combine these three short options, like I did here, but you can also specify them separately as `-x -z -f`.
In fact, many command-tools allow you to combine options that consist of a single character.

Indeed, `tar` is notorious for its many command-line arguments.
In this case, the three options `-x`, `-z`, and `-f` specify that `tar` should *extract* files from an archive, use *gzip* as the decompression algorithm and use file *logs.tar.gz*.

```{console tar_cancel, include=FALSE}
C-C #! literal=FALSE
```

However, since we're not yet familiar with this archive, it's a good idea to first examine its contents.
This can be done with the `-t` option (instead of the `-x` option):

```{console tar_t}
tar -tzf logs.tar.gz | trim
```

Is seems that this archive contains a lot of files, and they are not inside a directory.
In order to keep the current directory clean, it's a good idea to first create a new directory using `mkdir` and extract those files there using the `-C` option.

```{console tar_mkdir}
mkdir logs
tar -xzf logs.tar.gz -C logs
```

Let's verify the number of files and some of their contents:

```{console tar_verify}
ls logs | wc -l
cat logs/* | trim
```

Excellent.
Now, I understand that you'd like to scrub and explore these log files, but that's for later in [Chapter 5](#chapter-5-scrubbing-data) and [Chapter 7](#chapter-7-exploring-data).

In time, you'll get used to these options, but I'd like to show you an alternative option, which might be convenient.
Rather than remembering the different command-line tools and their options, there's a handy script called `unpack` [@unpack], which will decompress many different formats.
`unpack` looks at the extension of the file that you want to decompress, and calls the appropriate command-line tool.
Now, in order to decompress this same file, you would run:

```{console unpack}
unpack logs.tar.gz #! enter=FALSE
```

```{console unpack_cancel, include=FALSE}
C-C #! literal=FALSE
```


## Converting Microsoft Excel Spreadsheets to CSV

For many people, Microsoft Excel offers an intuitive way to work with small datasets and perform calculations on them.
As a result, a lot of data is embedded into Microsoft Excel spreadsheets.
These spreadsheets are, depending on the extension of the filename, stored in either a proprietary binary format (*.xls*) or as a collection of compressed XML files (*.xlsx*).
In both cases, the data is not readily usable by most command-line tools.
It would be a shame if we could not use those valuable datasets just because they are stored this way.

Especially when you're just starting out at the command line, you might be tempted to convert your spreadsheet to CSV by opening it in Microsoft Excel or an open source variant such as LibreOffice Calc, and manually exporting it to CSV.
While this works as a one-off solution, the disadvantage is that it does not scale well to multiple files and cannot be automated.
Furthermore, when you're working on a server, chances are that you don't have such an application available.
Trust me, you'll get the hang of it.

Luckily, there is a command-line tool called `in2csv`, that converts Microsoft Excel spreadsheets to CSV files.
CSV stands for comma-separated values.
Working with CSV can be tricky because it lacks a formal specification.
<!-- TODO: MUST: check and possibly fix reference? -->
Yakov Shafranovich defines the CSV format according to the following three points:[@shafranovich2005common]

1.  Each record is located on a separate line, delimited by a line break (`␊`). Take, for example, the following CSV file with crucial information about the Teenage Mutant Ninja Turtles:

```{console csv_1}
bat -A tmnt-basic.csv # <1>
```
<1> The `-A` option makes `bat` show all non-printable characters like spaces, tabs, and newlines.

2.  The last record in the file may or may not have an ending line break. For example:

```{console csv_2}
bat -A tmnt-missing-newline.csv
```

3.  There may be a header appearing as the first line of the file with the same format as normal record lines. This header will contain names corresponding to the fields in the file and should contain the same number of fields as the records in the rest of the file. For example:

```{console csv_3}
bat -A tmnt-with-header.csv
```

As you can see, CSV by default is not too readable.
You can pipe the data to a tool called `csvlook` [@csvlook], which will nicely format it into a table.
If the CSV data has no header, like *tmnt-missing-newline.csv* then you need to add the `-H` option, otherwise the first line will be interpreted as the header.

```{console csvlook}
csvlook tmnt-with-header.csv
csvlook tmnt-basic.csv
csvlook -H tmnt-missing-newline.csv # <1>
```
<1> The `-H` option specifies that the CSV file has no header.

Let’s demonstrate `in2csv` using a spreadsheet that contains the 2000 most popular songs according to an annual Dutch marathon radio program [Top 2000](https://www.top2000nl.com).
To extract its data, you invoke `in2csv` as follows:

```{console in2csv_save, remove=c("openpyxl", "silence", "behavior", "numpy", "guidance", "release")}
curl "https://www.nporadio2.nl/data/download/TOP-2000-2020.xlsx" > top2000.xlsx
in2csv top2000.xlsx | tee top2000.csv | trim
```

Who is Danny Vera? The most popular song is supposed to be *Bohemian Rhapsody*, of course.
Well, at least Queen appears plenty of times in the Top 2000 so I can't really complain:

```{console cvsgrep, callouts=1}
csvgrep top2000.csv --columns ARTIEST --regex '^Queen$' | csvlook -I
```
<1> The value after the `--regex` options is a regular expression (or *regex*). It's a special syntax for defining patterns. Here, I only want to match artists that exactly match "Queen", so I use the caret (`^`) and dollar sign (`$`) to match the start and end of the values in the column *`ARTIEST`*.

By the way, the tools `in2csv`, `csvgrep`, and `csvlook` are part of CSVkit, which is a collection of command-line tools to work with CSV data.

The format of the file is automatically determined by the extension, *.xlsx* in this case.
If you were to pipe the data into `in2csv`, you would have to specify the format explicitly.

A spreadsheet can contain multiple worksheets.
`in2csv` extracts, by default, the first worksheet.
To extract a different worksheet, you need to pass the name of worksheet to the `--sheet` option.
If you're not sure what's the worksheet is called, you can use the `--names` option, which prints the names of all the worksheets.
Here we see that *top2000.xlsx* has only one sheet, named *Blad1* (which is Dutch for *Sheet1*).

```{console in2csv_names, remove=c("openpyxl", "silence", "behavior", "numpy", "guidance", "release")}
in2csv --names top2000.xlsx
```


## Querying Relational Databases

Many companies store their data in a relational database.
Just as with spreadsheets, it would be great if we could obtain that data from the command line.

Examples of relational databases are MySQL, PostgreSQL, and SQLite.
These databases all have a slightly different way of interfacing with them.
Some provide a command-line tool or a command-line interface, while others do not.
Moreover, they are not very consistent when it comes to their usage and output.

Fortunately, there is a command-line tool called `sql2csv`, which is part of the CSVkit suite.
It works with many different databases through a common interface, including MySQL, Oracle, PostgreSQL, SQLite, Microsoft SQL Server, and Sybase.
The output of `sql2csv` is, as its name suggests, in CSV format.

We can obtain data from relational databases by executing a *`SELECT`* query on them.
(`sql2csv` also support *`INSERT`*, *`UPDATE`*, and *`DELETE`* queries, but that's not the purpose of this chapter.)

`sql2csv` needs two arguments: `--db`, which specifies the database URL, of which the typical form is: `dialect+driver://username:password@host:port/database` and `--query`, which contains the *`SELECT`* query.
For example, given an SQLite database that contains the standard datasets from R[^3] , I can select all the rows from the table *mtcars* and sort them by the *mpg* column as follows:

```{console sql2csv}
sql2csv --db 'sqlite:///r-datasets.db' \
--query 'SELECT row_names AS car, mpg FROM mtcars ORDER BY mpg' | csvlook
```

This SQLite database is a local file, so in this I don't need to specify any username, password or host.
If you wish to query the database of your employer, you'd of course need know how you can access it and you'd need the permission to do so.


## Calling Web APIs

In the previous section I explained how to download files from the Internet.
Another way data can come from the Internet is through a web API, which stands for *Application Programming Interface*.
The number of APIs that are being offered is growing at an increasing rate, which means a lot of interesting data for us data scientists.

Web APIs are not meant to be presented in a nice layout, such as websites.
Instead, most web APIs return data in a structured format, such as JSON or XML.
Having data in a structured form has the advantage that the data can be easily processed by other tools, such as `jq`.
For example, the API of Ice and Fire, which contains a lot of information about George R.R. Martin's fictional world, in which the Game of Thrones book and TV shows take place, returns data in the following JSON structure:

```{console curl_api, callouts="died"}
curl -s "https://anapioficeandfire.com/api/characters/583" | jq '.'
```
<1> Spoiler alert: this data is not entirely up-to-date.

The data is piped to a command-line tool `jq` just to display it in a nice way.
`jq` has many more scrubbing and exploring possibilities that I will explore in [Chapter 5](#chapter-5-scrubbing-data) and [Chapter 7](#chapter-7-exploring-data).


### Authentication

Some web APIs require you to authenticate (that is, to prove your identity) before you can consume their output.
There are several ways to do this.
Some web APIs use API keys while others use the OAuth protocol.
News API, an independent source of headlines and news articles, is a great example.
Let's see what happens when you try to access this API without an API key:

```{console curl_nokey}
curl -s "http://newsapi.org/v2/everything?q=linux" | jq .
```

Well, that was to be expected.
The part after the question mark, by the way, is where we pass any query parameters.
That's also the place where you need to specify an API key.
I'd like to keep my own API key a secret, so I insert it below by reading the file */data/.secret/newsapi.org_apikey* using command substitution.

```{console curl_auth}
curl -s "http://newsapi.org/v2/everything?q=linux&apiKey=$(< /data/.secret/newsapi.org_apikey)" |
jq '.' | trim 30
```
You can get your own API key at [News API's website](https://newsapi.org).


### Streaming APIs

Some web APIs return data in a streaming manner.
This means that once you connect to it, the data will continue to pour in, until the connection is closed.
A well-known example is the Twitter "firehose", which constantly streams all the tweets being sent around the world.
Luckily, most command-line tools also operate in a streaming matter.


```{console wikimedia_cp, include=FALSE}
 cp /data/.cache/wikimedia-stream-sample .
```

Let's take a 10 second sample of one of Wikimedia's streaming APIs, for example:

```{console wikimedia_curl}
curl -s "https://stream.wikimedia.org/v2/stream/recentchange" |
sample -s 10 > wikimedia-stream-sample #! enter=FALSE
```

```{console wikimedia_cancel, include=FALSE}
C-C #! literal=FALSE
```

This particular API returns all changes that have been made to Wikipedia and other properties of Wikimedia.
The command-line tool `sample` is used to close the connection after 10 seconds.
The connection can also be closed manually by pressing **`Ctrl-C`** to send an interrupt.
The output is saved to a file *wikimedia-stream-sample*.
Let's take a peek using `trim`:


```{console wikimedia_trim}
< wikimedia-stream-sample trim
```

With a little bit of `sed` and `jq` I can scrub this data to get a glimpse of the changes happening on the English version of Wikipedia:

```{console wikimedia_jq, callouts=c("sed", "jq")}
< wikimedia-stream-sample sed -n 's/^data: //p' |
jq 'select(.type == "edit" and .server_name == "en.wikipedia.org") | .title'
```
<1> This `sed` expression only prints lines that start with *`data: `* and prints the part after the semicolon, which happens to be JSON.
<2> This `jq` expression prints the *`title`* key of JSON objects that have a certain *`type`* and *`server_name`*.

Speaking of streaming, did you know that you could stream *Star Wars: Episode IV – A New Hope* for free using `telnet`[@telnet]?

```{console telnet_setup, include=FALSE}
 cd /data/.cache/
 alias telnet=echo
 print -S "telnet towel.blinkenlights.nl"
```

```{console telnet_cmd}
telnet towel.blinkenlights.nl#! enter=FALSE
```

And after some time, we see that Han Solo did shoot first!

```{console telnet_cancel, include=FALSE}
C-C#! literal=FALSE
```

```{console, remove=1}
 cat towel.blinkenlights.nl
```

Sure, it's probably not a good source of data, but there's nothing wrong with enjoying an old classic while training your machine learning models[^starwars].


## Summary

Congratulations, you have finished the first step of the OSEMN model.
You've learned a variety of ways to obtain data, ranging from downloading to querying a relational database.
In the next chapter, which is an intermezzo chapter, I'll teach you how to create your own command-line tools.
Feel free to skip this and go to [Chapter 5](#chapter-5-scrubbing-data) (the second step of the OSEMN model) if you cannot wait to learn about scrubbing data.


## For Further Exploration

- Looking for a dataset to practice on? The GitHub repository [*Awesome Public Datasets*](https://github.com/awesomedata/awesome-public-datasets) lists hundreds of high-quality datasets that are publicly available.
- Or perhaps you'd rather practice with an API? The GitHub repository [*Public APIs*](https://github.com/public-apis/public-apis) lists many free APIs. [City Bikes](http://api.citybik.es/v2/) and [The One API](https://the-one-api.dev/) are among my favorites.
- Writing SQL queries to obtain data from a relational database is an important skill. The first 15 lessons of the book *SQL in 10 Minutes a Day* by Ben Forta teach the *`SELECT`* statement and its filtering, grouping, and sorting capabilities.

[^3]: Available on [GitHub](https://github.com/r-dbi/RSQLite/blob/master/inst/db/datasets.sqlite).
[^starwars]: If you cannot connect to the server, because someone erased it from the archive memory, then you can always enjoy a [recording of the `telnet` session on YouTube](https://www.youtube.com/results?search_query=towel.blinkenlights.nl).
