#!/bin/bash
# explain: Command-line wrapper for explainshell.com
# 
# Example usage: explain tar xzvf 
#
# Dependency: scrape (from: https://github.com/jeroenjanssens/data-science-toolbox)
#
# Author: http://jeroenjanssens.com

COMMAND="$@"
URL="http://explainshell.com/explain?cmd=${COMMAND}"
curl -s "${URL}" | scrape -e 'span.dropdown > a, pre' | sed -re 's/<(\/?)[^>]*>//g'
