#!/usr/bin/env bash

# Rio-scatter: create scatter plot from CSV
# 
# Default colour is 1 (blue)
#
# Example usage:
# curl 'https://raw.githubusercontent.com/pydata/pandas/master/pandas/tests/data/iris.csv' | Rio-scatter SepalLength SepalWidth Name
#
# Dependency: Rio
#
# Author: http://jeroenjanssens.com

COLOUR=${3:-1}
Rio -ge "g+geom_point(aes(x=$1,y=$2,colour=${COLOUR}))"
