#!/usr/bin/env python
# sample: Output lines from stdin to stdout with a given probability, for a given duration, and with a given delay between lines.
# 
# Example usage: seq 100 | sample -r 20% -d 1000
#
# Dependency: Python 2.5
# 
# Author: http://jeroenjanssens.com

import os
import sys
import optparse

from random import random
from time import time, sleep
from sys import stdin, stdout
from datetime import datetime, timedelta

def total_seconds(delta):
   'Total seconds in the duration :param: delta.'
   return delta.seconds + (24 * 3600 * delta.days)

def main():
    parser = optparse.OptionParser()
    parser.add_option('-W', '--weeks', type=float, default=0, help="Duration of sampling in weeks")
    parser.add_option('-D', '--days', type=float, default=0, help="Duration of sampling in days")
    parser.add_option('-H', '--hours', type=float, default=0, help="Duration of sampling in hours")
    parser.add_option('-m', '--minutes', type=float, default=0, help="Duration of sampling in minutes")
    parser.add_option('-s', '--seconds', type=float, default=0, help="Duration of sampling in seconds")
    parser.add_option('-t', '--milliseconds', type=float, default=0, help="Duration of sampling in milliseconds")
    parser.add_option('-u', '--microseconds', type=float, default=0, help="Duration of sampling in microseconds")
    parser.add_option('-r', '--rate', default='100%', help="Rate between 0 and 1 using either 0.33, 33%, 1/3 notation.")
    parser.add_option('-d', '--delay', default=0, type=int, help="Time in milliseconds between each line of output")
    args, cmds = parser.parse_args()

    try:
        delay = (float(args.delay) / 1000.0)
    except ValueError:
        parser.error("Invalid delay. Please specify a delay in ms.")
        
    try:
        duration = total_seconds(timedelta(weeks=args.weeks, days=args.days,
	    hours=args.hours, minutes=args.minutes, seconds=args.seconds,
	    milliseconds=args.milliseconds, microseconds=args.microseconds))
    except:
        parser.error("Invalid duration.")

    try:
        if '%' in args.rate:
            rate = float(args.rate[:-1]) / 100.0
        elif '/' in args.rate:
            a, b = map(float, args.rate.split('/')[:2])
            rate = a / (1.0*b)
        else:
            rate = float(args.rate)
    except ValueError:
        parser.error("Invalid rate. Please specify a rate between 0 and 1 using either 0.33, 33%, 1/3 notation.")

    if rate <= 0 or rate > 1:
        parser.error("Invalid rate. Please specify a rate between 0 and 1 using either 0.33, 33%, 1/3 notation.")

    start = time()
    try:
        while True:
            line = sys.stdin.readline()
            if not line:
                return
            if random() <= rate:
                sys.stdout.write(line)
                sys.stdout.flush()
                now = time()
                if duration and (now-start) > duration:
                    return
                sleep(delay)
    except:
        pass

if __name__ == "__main__":
    exit(main())
