#!/usr/bin/env bash
#
# Tapkee is an efficient dimension reduction library. This Bash script makes
# tapkee_cli, its command-line interface, play nice with standard input and
# standard output. Moreover, input is now assumed to be CSV with no header,
# where each line is a data point, and each column is a feature.
# Command-line arguments, such as --method, are passed onto tapkee_cli.
# 
# Author: Jeroen Janssens (http://jeroenjanssens.com)
#
# Dependencies:
# - Tapkee (see http://tapkee.lisitsyn.me for installation instructions)
# - Rio-transpose (to transpose the input and output, see https://github.com/
#   jeroenjanssens/command-line-tools-for-data-science/tree/master/tools)
#
# Example usage: 
# $ < iris-original.csv tapkee --method t-sne > iris-mapped.csv

OUT=$(mktemp --tmpdir tapkee-XXXXXXXX).dat
Rio-transpose | tr , ' ' | tapkee_cli -i /dev/stdin -o $OUT "$@" > /dev/null
sed -re 's/^\s+//;s/\s+/,/g' $OUT | Rio-transpose
rm $OUT
